[config]
schemaVersion = "0.0.1"

[package]
namespace = "MGReturns"
name = "SeerSuite"
versionNumber = "1.0.3"
description = "Defines debug tools such as an Object Browser and Script Console."
websiteUrl = "https://github.com/AndreLouisIssa/RoRR-SeerSuite"
containsNsfwContent = false

[package.dependencies]
ReturnOfModding-ReturnOfModding = "1.0.38"
MGReturns-ENVY = "1.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "risk-of-rain-returns", ]

[publish.categories]
hades-ii = [ "libraries", "mods" ]
